INSERT INTO questions (description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Une jeune femme arrive dans une réunion pour la première fois depuis sa prise de poste. Son maître d’apprentissage l’accueille et lui dit : « Bonjour, bienvenue, je suis ravi, tu seras la seule femme présente pour notre réunion de service, aussi, tu feras le compte-rendu ». Il s’agit d’un acte se rapportant à :',
        'Agissement sexiste', 'Agissement sexiste', 'Demande professionnelle', 'Agression sexuelle ',
        'Harcèlement sexuel',
        'Il s’agit d’un agissement sexiste, défini comme tout agissement lié au sexe d’une personne, ayant pour objet ou pour effet de porter atteinte à sa dignité ou de créer un environnement intimidant, hostile, dégradant humiliant ou offensant. Sous prétexte qu’elle soit la seule femme de la réunion, son maître d’apprentissage lui demande de faire le compte-rendu. La demande ne tient pas compte de ses compétences mais de son sexe. Ce type de comportement n’a pas lieu d’être dans le monde du travail. De tels agissements peuvent affecter le collectif de travail (ambiance, clivages, absences, anxiété généralisée) et entraîner pour la victime des impacts psychologiques et sur le travail.');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Le comité de Direction se réunit pour valider le choix d’un prestataire informatique. L’un des membres du comité prend la parole en imitant l’un des prestataires présélectionnés, d’une voix aigüe : « la proposition du cabinet Martin est intéressante mais le chef de projet manque de virilité si vous voyez ce que je veux dire ! » Il s’agit d’une agression sexuelle :',
        'Agissement sexiste', 'FAUX', 'VRAI', NULL, NULL,
        'Faux, c’est un agissement sexiste. Si les agissements sexistes sont majoritairement fondés sur le sexe, ils peuvent aussi être fondés sur l’orientation sexuelle ou l’identité de genre (personnes lesbiennes, gays, bisexuelles, transidentitaires…). Dans le cas présenté, ce membre du comité remet en question le chef de projet en raison de son manque supposé de virilité et ce faisant le discrédite. Il ne fait pas référence à ses compétences.');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Lors de son entretien annuel, une collaboratrice s’entend dire par son manager : « j’apprécie de travailler avec vous, comme toutes les femmes, vous êtes douce, discrète, sensible.» Il s’agit:',
        'Agissement sexiste', 'Agissement sexiste', 'Compliment', 'Agression sexuelle', 'Remarque objective',
        'Même si les propos peuvent sembler flatteurs, il s’agit bien d’un agissement sexiste et plus particulièrement de sexisme bienveillant. Il est basé sur l’attribution de qualités et rôles spécifiques, dits « complémentaires », entre les hommes et les femmes. Dans cette situation, les qualités évoquées par le manager ne relèvent pas de compétences professionnelles mais de qualités qu’il considère être celles des femmes. Il s’agit de propos fondés sur des stéréotypes de sexe. La collaboratrice peut se sentir délégitimée, rabaissée, dévalorisée ce qui peut entrainer des impacts sur sa santé physique et mentale.');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Le fils d’une employée est malade et l’école lui demande de venir le chercher ; il est 15h. Son collègue, d’un ton agacé, lui dit : « Vous les femmes vous avez un prétexte tout trouvé pour quitter le travail en pleine après-midi, ça sert d’avoir des gosses ! » Il s’agit d’un agissement sexiste :',
        'Agissement sexiste', 'VRAI', 'FAUX', NULL, NULL,
        'Vrai, il s’agit d’un agissement sexiste dit « hostile » caractérisé par une attitude négative explicite à l’égard des femmes ou des hommes. Il est intentionnel, visible et il s’exprime ouvertement. Cette situation illustre une considération sexiste sur les charges familiales, elle a pour effet de créer un environnement de travail hostile pour Mathilde qui peut avoir des impacts psychologiques et physiques, des conséquences sur son travail, voire sur sa vie privée. Et plus largement, de tels comportements risquent d’affecter le collectif de travail, les autres femmes du service pouvant se sentir indirectement visées.');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Lors d’une réunion d’équipe, une collaboratrice, en rigolant, dit d’un de ses collègue: «  il ne peut pas faire le café, c’est bien connu, les mecs ne savent vraiment pas faire deux choses en même temps !». Il s’agit d’un agissement sexiste :',
        'Agissements sexistes', 'VRAI', 'FAUX', NULL, NULL,
        'Vrai, il s’agit de sexisme dit « masqué ». Il a pour objet de traiter un sexe de manière défavorable par rapport à l’autre sexe, mais de manière volontairement camouflée. Il se traduit par des remarques et des blagues sexistes sous couvert de l’humour, l’affectation des femmes et des hommes à certaines tâches conformes aux stéréotypes de sexe, l’exclusion ou l’infériorisation.Dans cette situation, Benjamin peut se sentir délégitimé, infériorisé, dévalorisé. Tout comme le sexisme « bienveillant » ou le sexisme « hostile », le sexisme « masqué » peut avoir des effets néfastes tant sur l’environnement de travail que sur la santé physique et mentale des personnes.');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('L’auteur d’agissement sexiste peut faire l’objet d’une sanction disciplinaire mais ne peut pas être licencié. Est-ce :',
        'Agissement sexiste', 'FAUX ', 'VRAI', NULL, NULL,
        'Faux, l’auteur d’agissement sexiste peut faire l’objet d’une sanction disciplinaire de la part de son employeur pouvant aller du simple avertissement et blâme jusqu’au licenciement. Constitue une sanction toute mesure, autre que les observations verbales, prise par l’employeur à la suite d’un agissement de salarié considéré par l’employeur comme fautif que cette mesure soit de nature à affecter immédiatement ou non la présence du salarié dans l’entreprise, sa fonction, sa carrière ou sa rémunération. Sur le plan pénal, le fait d’imposer à une personne tout propos ou comportement à connotation sexuelle ou sexiste qui, soit porte atteinte à sa dignité en raison de son caractère dégradant ou humiliant, soit créé à son encontre une situation intimidante, hostile ou offensante est considéré comme un « outrage sexiste ». Il est puni d’une amende allant de 750 à 1 500 euros; des peines complémentaires peuvent être prononcées.');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Une collaboratrice invite son collègue à dîner. Ce dernier refuse poliment. Elle lui adresse alors, chaque matin un sms pour lui souhaiter une bonne journée ou le complimenter sur sa tenue. LE collègue en question lui demande de stopper toutes ces attentions déplacées. Elle profite alors de son anniversaire de pour lui offrir un coffret de parfum et l’inviter à passer un week-end dans sa maison de bord de mer. Il s’agit :',
        'Harcèlement sexuel', 'Harcèlement sexuel ', 'Agissement sexiste', 'Agression sexuelle ', 'Acte de séduction',
        'Il s’agit précisément de faits assimilés au harcèlement sexuel, qui consistent en toute forme de pression grave, exercée dans le but réel ou apparent d’obtenir un acte de nature sexuelle, que celui-ci soit recherché au profit de l’auteur des faits ou au profit d’un tiers. De même, des propos écrits répétés exprimant le désir explicite d’avoir une relation d’ordre sexuel avec un, une collègue, en dépit de ses refus réitérés constituent des faits de harcèlement sexuel. Dans cette situation, Serge subit le harcèlement sexuel de sa collègue Yolande : elle continue en effet à solliciter Serge, bien qu’il lui ait demandé d’arrêter ses actions déplacées.');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Le harcèlement sexuel est lié exclusivement au fait d’exiger d’une personne des faveurs sexuelles.',
        'Harcèlement sexuel ', 'FAUX', 'VRAI', NULL, NULL,
        'Faux. Le harcèlement sexuel n’est pas exclusivement lié au fait d’exiger des faveurs sexuelles. Il peut aussi consister dans des propos ou comportements à connotation sexuelle non désirés et répétés qui portent atteinte à la dignité de la personne ou créent une situation intimidante, hostile ou offensante. Par exemple : le fait d’insister sur le physique d’une personne, d’évoquer de manière répétée ses expériences ou désirs sexuels, ou encore, de tenir des propos obscènes.');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Lors d’un entretien, un manager dit clairement à son employée : « Votre travail donne entièrement satisfaction à l’entreprise, vous êtes reconnue par tous pour votre professionnalisme. Sachez qu’un poste de Responsable de service s’ouvre et j’ai pensé à vous. Je vous invite à dîner pour en discuter, nous pourrons faire plus ample connaissance …! » Il s’agit :',
        'Harcèlement sexuel ', 'Harcèlement sexuel ', 'Agissement sexiste', 'Acte de séduction', 'Agression sexuelle ',
        'Il s’agit de harcèlement sexuel. Le Code du travail distingue «les faits de harcèlement sexuel » des « faits assimilés au harcèlement sexuel ». La situation illustre des faits assimilés au harcèlement sexuel. Dans cette situation, le manager se sert de sa fonction hiérarchique pour obtenir les faveurs sexuelles. Il s’agit de la manifestation d’un rapport de pouvoir où le manager cherche à s’imposer, à dominer par une forme de chantage. Il ne cherche pas le consentement de son employée. En raison de sa gravité, un acte isolé suffit à caractériser le harcèlement sexuel.');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Un salarié ou une salariée peut faire l’objet d’une sanction disciplinaire pour des faits de harcèlement sexuel intervenus à l’encontre d’un ou d’une collègue de travail, en dehors du temps de travail. Est-ce :',
        'Harcèlement sexuel', 'VRAI', 'FAUX', NULL, NULL,
        'Vrai, les propos à caractère sexuel et les attitudes déplacées d’un salarié à l’égard de personnes avec lesquelles il est en contact en raison de son travail et intervenus en dehors du temps  et/ou du lieu ne relèvent pas que de sa vie personnelle. Le harcèlement sexuel au travail peut être constaté en tous lieux pendant ou en hors temps de travail.');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Vous êtes témoin de fait de harcèlement sexuel sur l’une de vos collègues, ce n’est pas votre rôle d’intervenir sur ce genre de situation.',
        'Harcèlement sexuel ', 'FAUX', 'VRAI', NULL, NULL,
        'Faux. En tant que témoin, vous jouez un rôle clé dans la résolution d’une situation de harcèlement sexuel et bénéficiez à ce titre d’une protection juridique particulière : « Aucun salarié, aucune personne en formation ou en stage ne peut-être sanctionné, licencié ou faire l’objet d’une mesure discriminante pour avoir témoigné de faits de harcèlement sexuel ou pour les avoir relatés . « Toute disposition ou tout acte contraire (…) est nul ». Le Code du travail indique : « l’employeur prend toutes dispositions nécessaires en vue de prévenir les faits de harcèlement sexuel, d’y mettre un terme et de les sanctionner ». Ainsi, l’employeur et ses représentants doivent prendre des mesures immédiates propres à faire cesser le harcèlement dès qu’ils en sont informés, sous peine de voir leur responsabilité engagée devant le juge civil.');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Un collègue complimente sa voisine de bureau sur sa nouvelle coiffure et l’invite à prendre un verre après le travail. Celle ci le remercie et décline l’invitation. Il accepte le refus en hochant de la tête. Leurs relations de travail reprennent normalement. Il s’agit :',
        'Harcèlement sexuel ', 'Acte de séduction', 'Harcèlement sexuel', 'Agissement sexiste', NULL,
        'Il s’agit d’une simple manœuvre de séduction. « Lorsqu’une personne souhaite séduire une autre personne, elle a des propos et des comportements positifs et respectueux. Les relations souhaitées sont égalitaires et réciproques, donc consenties. A l’inverse, le harceleur ne cherche pas à séduire ou à plaire, il veut imposer ses choix et son pouvoir. Il nie l’autre. En résumé, la séduction est un rapport d’égalité alors que le harcèlement sexuel repose sur un rapport de domination, sans consentement mutuel. ». Dans la situation, la femme ne souhaite pas de relation personnelle avec son collègue. Elle l’exprime et il accepte, sans insister. Le choix de la femme est ainsi respecté.');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Tous les matins dans son open-space, malgré le malaise visible chez certains de ses collègues, un des collaborateurs raconte une histoire grivoise voire obscène. Il s’agit :',
        'Harcèlement sexuel ', 'Harcèlement sexuel', 'Agissement sexiste', 'Agression sexuelle',
        'Blague sans conséquence',
        'Il s’agit d’un agissement sexiste et d’un harcèlement sexuel dit « harcèlement sexuel d’ambiance », qui se traduit par des propos et des agissements répétés à connotation sexuelle pouvant constituer un environnement de harcèlement « intimidant, hostile, dégradant, humiliant ou offensant ». Dans cette situation, les collègues de l’open-space peuvent se sentir délégitimés, infériorisés, dévalorisés même si ils ne sont pas directement visés par ses blagues grivoises. Les trois collègues peuvent être mal à l’aise et l’environnement de travail peut être considéré comme intimidant, hostile, dégradant, humiliant ou offensant. Des effets sur leur santé physique ou mentale et des conséquences sur le travail, voire sur leur vie privée, peuvent en découler.');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Le harcèlement sexuel est un délit pénal, ces auteurs encourent une peine de 2 à 3 ans d’emprisonnement et de 30 000 € à 45 000 € d’amende.',
        'Juridique', 'VRAI', 'FAUX', NULL, NULL,
        'Vrai. En application de l’article 222-33 du code pénal, les auteurs de harcèlement sexuel encourent une peine de 2 ans d’emprisonnement et de 30 000 € d’amende qui peut être portée à 3 ans d’emprisonnement et 45 000 € d’amende lorsque les faits sont commis : par une personne qui abuse de l’autorité que lui confèrent ses fonctions ;sur un mineur de moins de quinze ans ;sur une personne vulnérable notamment en raison de son âge, d’une maladie, de son état de grossesse ou de sa situation économique ou sociale ;par plusieurs personnes agissant en qualité d’auteur ou de complice ;par toute autre personne ayant sur la victime une autorité de droit ou de fait.');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Un homme envoie des messages érotiques tous les jours à sa collègue par SMS. Elle n’a jamais exprimé le souhait de les recevoir. Il s’agit:',
        'Harcèlement sexuel ', 'Harcèlement sexuel ', 'Agissement sexiste', 'Agression sexuelle', NULL,
        'Le denvoyer à répétition des messages à caratcères sexuels à un de ses collègues participe à une forme de harcèlement sexuel, cela peut avoir de graves conséquences sur la victime tant sur son moral personnel que dans son épnousissement professionnel car cela risque de la rendre mal à l’aise sur son lieu de travail.');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Le harcèlement sexuel est le fait d’ ............... à une personne, de façon ............... , des propos ou comportements à connotation ............... qui soit portent atteinte à sa dignité en raison de leur caractère dégradant ou humiliant, soit créent à son encontre une situation intimidante, hostile ou offensante.',
        'Harcèlement sexuel ', 'imposer | répétée | sexuelle', 'demander | unique | rabaissante',
        'obliger | régulière | mysogine', NULL,
        'Définition du harcèlement sexuel par le code pénal');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Lorsqu’un(e) employée arrive son lieu de travail, certains des collaborateurs l’interpellent en l’appelant “ma jolie”, “ma beauté” ou “ma mignonne” et cela la rend mal à l’aise. De quoi s’agit-il?',
        'Harcèlement sexuel', 'Harcèlement sexuel', 'Agissement sexiste', 'Acte de séduction lourd', NULL,
        'Ce comportement est défini dans le code du travail depuis 2015 comme un "agissement sexiste". Il peut être puni d’une sanction de l’employeur. Depuis l’été 2018, les propos ou comportements sexistes sont intégrés à la définition du harcèlement sexuel. Si ces propos portent atteinte à la dignité de la victime, et qu’ils sont répétés, ils peuvent être donc être considérés comme du harcèlement sexuel et punis de 2 ans d’emprisonnement.');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Deux employés de sexe opposés se retrouvent dans l’ascenseur avec plusieurs autres collègues, L’un se rapproche de l’autre et en profite pour lui effleurer les fesses. Il s’agit :',
        'Agression sexuelle', 'Agression sexuelle', 'Agissement sexiste', 'Harcèlement sexuel', NULL,
        'Il s’agit d’une agression sexuelle définie comme toute atteinte sexuelle commise avec violence, contrainte, menace ou surprise. Selon la jurisprudence, l’atteinte sexuelle peut concerner 5 parties du corps : fesses, sexe, poitrine, cuisses, bouche. Dans la situation décrite, Victor commet une atteinte sexuelle avec surprise.');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Un manager est attiré par son assistante. Pendant la pause déjeuner, alors qu’ils sont seuls dans le bureau, il se jette sur elle et l’embrasse sur la bouche, sans son consentement. Il s’agit d’une agression sexuelle, Florent peut encourir :',
        'Agression sexuelle', '10 ans de prison et 150 000 euros d’amende', '5 ans de prison et 75 000 euros d’amende',
        '2 ans de prison et 10 000 euros d’amende', NULL,
        'L’auteur d’une agression sexuelle risque 5 ans de prison et 75 000 € d’amende, mais en cas de circonstances aggravantes, la peine peut être portée à 10 ans d’emprisonnement et 150 000 euros d’amende. Des peines complémentaires peuvent être imposées (ex : injonction de soins, interdiction de séjour dans certains lieux,…). La personne condamnée figurera également au fichier des auteurs d’infractions sexuelles. Dans la situation, la supériorité hiérarchique du manager est une circonstance aggravante qui peut porter sa peine à 7 ans d’emprisonnement et 100 000 euros d’amende. Si la scrétaire est dans une situation particulière de vulnérabilité connue de son supérieur (ex :  état de grossesse, situation économique et sociale précaire), la peine pourrait être portée à 10 ans d’emprisonnement et 150 000 euros d’amende. »');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Aux yeux de la loi, l’agression sexuelle se caractérise par des attouchements faits avec violence, menace, contrainte ou surprise sur les parties du corps à connotation sexuelles qui sont : ',
        'Agression sexuel ', 'Bouche - Poitrine - Fesses - Sexe - Cuisses', 'Bouche - Epaules - Poitirne - Sexe - Dos',
        'Cheveux - Epaules - Poitrine - Fesses - Sexe', 'Cheveux - Bouche - Poitine - Sexe - Fesses',
        'En réalité peu importe la partie du corps concernée par les attouchements, si cela ne correspond pas à une agression sexuelle, les attouchements à répétition de n’importe quelle partie du corps de la victime sera considéré comme harcèlement sexuel et sera puni tout comme l’agression.');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Un référent en matière de lutte contre le harcèlement sexuel et les agissements sexistes doit être désigné par l’employeur dans les entreprises d’au moins 250 salariés, et par les représentants du personnel au sein de chaque comité social et économique (CSE).',
        'Accompagnement', 'VRAI', 'FAUX', NULL, NULL,
        'Vrai. Les textes de lois prévoient deux référents distincts, le Référent entreprise et le Référent CSE. Pour le référent entreprise : Dans toutes les entreprises employant au moins 250 salariés est désigné un référent chargé d’orienter, d’informer et d’accompagner les salariés en matière de lutte contre le harcèlement sexuel et les agissements sexistes. Pour le référent CSE : pour toutes les entreprises dotées d’un comité social et économique (CSE) : la nomination, en son sein, d’un référent en matière de lutte contre le harcèlement sexuel et les agissements sexistes est obligatoire.Les salariés de l’entreprise doivent être informés du nom, des coordonnées et des missions des référents en poste.');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Les salariés doivent obligatoirement être informés du nom et des coordonnées (adresse et numéro d’appel) des interlocuteurs suivants : du référent contre le harcèlement sexuel et les agissements sexistes de votre entreprise, du référent contre le harcèlement sexuel et les agissements sexistes du Comité Social et Economique (CSE), du service de santé au travail (médecin du travail, infirmier, assistant social), de l’inspection du travail et du Défenseur des droits.',
        'Accompagnement', 'VRAI', 'FAUX', NULL, NULL,
        'Vrai. Dans tous les lieux de travail ainsi que dans les locaux ou à la porte des locaux où se fait l’embauche, les salariés, personnes en formation ou en stage, les candidats à un recrutement, sont informés par tout moyen du texte de l’article 222-33 du code pénal (harcèlement sexuel), ainsi que des actions contentieuses civiles et pénales ouvertes en matière de harcèlement sexuel  et des coordonnées des autorités et services compétents. Le Code du travail indique que l’information doit préciser l’adresse et le numéro d’appel du médecin du travail, de l’inspection du travail, du défenseur des droits, du référent contre le harcèlement sexuel et les agissements sexistes de votre entreprise et du référent contre le harcèlement sexuel et les agissements sexistes du Comité Social et Economique.');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Un collaborateur a accroché dans les bureaux des posters de femmes dénudées, c’est à la vue de tout le monde lorsqu’ils passent devant son bureau. De quoi s’agit-il?',
        'Harcèlement sexuel', 'Harcèlement sexuel', 'Agissement sexiste', 'Acte d’exhibitionnisme',
        'Agression sexuelle',
        'Le droit français permet de se plaindre de cette forme de harcèlement sexuel, c’est une forme environnementale. Les salarié.e.s sont légitimes à considérer qu’ils ou elles n’ont pas à travailler dans cet environnement.');
INSERT INTO questions(description, theme, bonne_reponse, reponse_2, reponse_3, reponse_4, explication)
VALUES ('Un employé envoie des e-mails collectifs comportant des blagues salaces ou des images pornographiques, « pour faire rire les collègues ». Une collègue lui demande de cesser de lui adresser ce type de messages.',
        'Harcèlement sexuel', 'Harcèlement sexuel', 'Agression sexuelle', 'Agissement sexiste',
        'Acte d’exhibitionnisme',
        'Tout comme l’affichage d’un calendrier avec des images pornographiques ou l’affichage de fonds d’écran mettant en scène de la nudité, le fait d’envoyer des e-mails comportant des blagues salaces, dégradantes ou humiliantes constitue du harcèlement sexuel d’ambiance. Nul besoin que ces propos visent une personne de l’entreprise. Nul besoin non plus d’avoir à opposer un refus explicite à recevoir ce type de communications. Seule compte la capacité de la victime à prouver que ces envois portent atteinte à la dignité.');